### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [ayush--s/gh_stars_export#2]
```$ gh_stars_export.py -o gh_stars.json --token blahblahblab 

Traceback (most recent call last):
  File "/usr/local/bin/gh_stars_export.py", line 80, in <module>
    main()
  File "/usr/local/bin/gh_stars_export.py", line 76, in main
    export_stars(args)
  File "/usr/local/bin/gh_stars_export.py", line 61, in export_stars
    export_as_json(stars, args.outfile)
  File "/usr/local/bin/gh_stars_export.py", line 49, in export_as_json
    write_to_file(filepath, data)
  File "/usr/local/bin/gh_stars_export.py", line 27, in write_to_file
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by ghost** [comment]
The same error on both Windows 10 and Ubuntu, if mentioning this helps at all.

**Comment by drjasonharrison-vp-eio** [comment]
My crash was on macos. Perhaps there is a specific version of Python expected? 2.7 is end of life.

**Comment by ayush--s** [comment]
I intended to [support only python3](https://github.com/ayush--s/gh_stars_export/blob/master/setup.py#L24), but missed on not allowing installs on python<= 2.7. I'll make that change this weekend.  
You'll have to install this on python3 for it to work.
